"""empty message

Revision ID: 604fbaa64f29
Revises: 
Create Date: 2023-12-23 13:18:31.968903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604fbaa64f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('emprestado_para', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sala', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=255), nullable=True),
    sa.Column('adm', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_emprestados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_emprestados')
    op.drop_table('pessoa')
    op.drop_table('livros')
    # ### end Alembic commands ###
