"""Adicionando a coluna emprestado_para_id à tabela livros

Revision ID: 6cbe53831a00
Revises: 
Create Date: 2025-02-13 11:24:07.712048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbe53831a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa')
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emprestado_para_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_emprestado_para', 'pessoa', ['emprestado_para_id'], ['id'])
        batch_op.drop_column('emprestado_para')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emprestado_para', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emprestado_para_id')

    op.create_table('pessoas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sala', sa.VARCHAR(length=255), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    # ### end Alembic commands ###
