"""empty message

Revision ID: 849ae9dcd2ae
Revises: 
Create Date: 2023-12-21 21:51:11.418601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849ae9dcd2ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_emprestados')
    op.drop_table('livros')
    op.drop_table('pessoa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sala', sa.VARCHAR(length=255), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=255), nullable=True),
    sa.Column('adm', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('autor', sa.TEXT(), nullable=False),
    sa.Column('genero', sa.TEXT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('emprestado_para', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_emprestados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pessoa_id', sa.INTEGER(), nullable=False),
    sa.Column('livro_id', sa.INTEGER(), nullable=False),
    sa.Column('data_devolucao', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
