"""empty message

Revision ID: facc18492514
Revises: 849ae9dcd2ae
Create Date: 2023-12-23 09:57:37.138172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facc18492514'
down_revision = '849ae9dcd2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    op.drop_table('pessoa')
    op.drop_table('livros_emprestados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros_emprestados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pessoa_id', sa.INTEGER(), nullable=False),
    sa.Column('livro_id', sa.INTEGER(), nullable=False),
    sa.Column('data_devolucao', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sala', sa.VARCHAR(length=255), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=255), nullable=True),
    sa.Column('adm', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('autor', sa.VARCHAR(length=255), nullable=False),
    sa.Column('genero', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('emprestado_para', sa.VARCHAR(length=255), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
