name: CI Pipeline

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - CI

jobs:

  sync-alpha:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Pull from alpha
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git fetch origin alpha
            git merge origin/alpha
            git push origin CI

  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código da branch
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Executar os testes
      - name: Run Unit Tests
        run: |
          pytest tests/unit

      - name: Run Integration Tests
        run: |
          pytest tests/integration

      - name: Run End-to-End Tests
        run: |
          pytest tests/e2e

      - name: Run Performance Tests
        run: |
          pytest tests/performance
